name: Deploy Test Apache
on:
  push:
    branches:
      - main
      - dev

jobs:
  test-apache-manifests:
    uses: JHOFER-Cloud/helm-ci/.github/workflows/k8s-deploy-template.yml@v3.0.2-dev.1
    with:
      helm-ci_image_tag: 3.0.2-dev.1
      app_name: test-apache
      custom_deployment: true
      values_path: manifests
      vault_url: https://vault.dev.k8.hla1.jhofer.lan
      vault_base_path: talos
    secrets:
      KUBE_CONFIG_DEV: ${{ secrets.KUBE_CONFIG_DEV }}
      KUBE_CONFIG_LIVE: ${{ secrets.KUBE_CONFIG_DEV }}
      VAULT_TOKEN: ${{ secrets.HLA1_VAULT }}
  test-apache:
    needs: test-apache-manifests
    uses: JHOFER-Cloud/helm-ci/.github/workflows/k8s-deploy-template.yml@v3.0.2-dev.1
    with:
      helm-ci_image_tag: 3.0.2-dev.1
      app_name: test-apache
      helm_repository: oci://registry-1.docker.io/bitnamicharts
      helm_chart: apache
      helm_version: 11.3.4
      values_path: helm/values
      live_domains: live.k8.hla1.jhofer.lan, live.hla1.jhofer.lan
      dev_domains: dev.k8.hla1.jhofer.lan, dev.hla1.jhofer.lan
      domain_template: bitnami
      # root_ca: "http://pki.jhofer.lan/certs/root-ca.pem"
      # test_url_path: "dashboard/#/"
      pr_deployments: false
    secrets:
      KUBE_CONFIG_DEV: ${{ secrets.KUBE_CONFIG_DEV }}
      KUBE_CONFIG_LIVE: ${{ secrets.KUBE_CONFIG_DEV }}
